---
name: Testing and Linting

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.2     

      - name: Installdependencies
        run: python -m pip install --upgrade pip && pip install flake8
      - name: Run Flake8
        working-directory: ./backend
        run: flake8
